//This file is automatically generated by CMAKE. DO NOT MODIFY.
using System;
using System.Collections.Generic;

namespace Emgu.CV
{
   public partial class CvInvoke
   {
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string ExternLibrary = "cvextern";
	  
	  /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string ExternCudaLibrary = ExternLibrary;

      /// <summary>
      /// The file name of the opencv_ffmpeg library
      /// </summary>
      public const string OpencvFFMpegLibrary = "opencv_ffmpeg300_64";

	   
      /// <summary>
      /// The file name of the OpenCL library
      /// </summary>
      public const string OpenclLibrary = "OpenCL"; 
      /// <summary>
      /// The file name of the core library
      /// </summary>
      public const string OpencvCoreLibrary = "opencv_core300"; 
      /// <summary>
      /// The file name of the imgproc library
      /// </summary>
      public const string OpencvImgprocLibrary = "opencv_imgproc300"; 
      /// <summary>
      /// The file name of the video library
      /// </summary>
      public const string OpencvVideoLibrary = "opencv_video300"; 
      /// <summary>
      /// The file name of the flann library
      /// </summary>
      public const string OpencvFlannLibrary = "opencv_flann300"; 
      /// <summary>
      /// The file name of the ml library
      /// </summary>
      public const string OpencvMlLibrary = "opencv_ml300"; 
      /// <summary>
      /// The file name of the imgcodecs library
      /// </summary>
      public const string OpencvImgcodecsLibrary = "opencv_imgcodecs300"; 
      /// <summary>
      /// The file name of the videoio library
      /// </summary>
      public const string OpencvVideoioLibrary = "opencv_videoio300"; 
      /// <summary>
      /// The file name of the highgui library
      /// </summary>
      public const string OpencvHighguiLibrary = "opencv_highgui300"; 
      /// <summary>
      /// The file name of the objdetect library
      /// </summary>
      public const string OpencvObjdetectLibrary = "opencv_objdetect300"; 
      /// <summary>
      /// The file name of the features2d library
      /// </summary>
      public const string OpencvFeatures2dLibrary = "opencv_features2d300"; 
      /// <summary>
      /// The file name of the calib3d library
      /// </summary>
      public const string OpencvCalib3dLibrary = "opencv_calib3d300"; 
      /// <summary>
      /// The file name of the cudalegacy library
      /// </summary>
      public const string OpencvCudalegacyLibrary = "opencv_cudalegacy300"; 
      /// <summary>
      /// The file name of the cudaarithm library
      /// </summary>
      public const string OpencvCudaarithmLibrary = "opencv_cudaarithm300"; 
      /// <summary>
      /// The file name of the cudawarping library
      /// </summary>
      public const string OpencvCudawarpingLibrary = "opencv_cudawarping300"; 
      /// <summary>
      /// The file name of the cuda library
      /// </summary>
      public const string OpencvCudaLibrary = "opencv_cuda300"; 
      /// <summary>
      /// The file name of the cudafilters library
      /// </summary>
      public const string OpencvCudafiltersLibrary = "opencv_cudafilters300"; 
      /// <summary>
      /// The file name of the cudaimgproc library
      /// </summary>
      public const string OpencvCudaimgprocLibrary = "opencv_cudaimgproc300"; 
      /// <summary>
      /// The file name of the cudaoptflow library
      /// </summary>
      public const string OpencvCudaoptflowLibrary = "opencv_cudaoptflow300"; 
      /// <summary>
      /// The file name of the cudastereo library
      /// </summary>
      public const string OpencvCudastereoLibrary = "opencv_cudastereo300"; 
      /// <summary>
      /// The file name of the cudabgsegm library
      /// </summary>
      public const string OpencvCudabgsegmLibrary = "opencv_cudabgsegm300"; 
      /// <summary>
      /// The file name of the cudafeatures2d library
      /// </summary>
      public const string OpencvCudafeatures2dLibrary = "opencv_cudafeatures2d300"; 
      /// <summary>
      /// The file name of the photo library
      /// </summary>
      public const string OpencvPhotoLibrary = "opencv_photo300"; 
      /// <summary>
      /// The file name of the superres library
      /// </summary>
      public const string OpencvSuperresLibrary = "opencv_superres300"; 
      /// <summary>
      /// The file name of the stitching library
      /// </summary>
      public const string OpencvStitchingLibrary = "opencv_stitching300"; 
      /// <summary>
      /// The file name of the videostab library
      /// </summary>
      public const string OpencvVideostabLibrary = "opencv_videostab300"; 
      /// <summary>
      /// The file name of the shape library
      /// </summary>
      public const string OpencvShapeLibrary = "opencv_shape300"; 
      /// <summary>
      /// The file name of the cudev library
      /// </summary>
      public const string OpencvCudevLibrary = "opencv_cudev300"; 
      /// <summary>
      /// The file name of the cudacodec library
      /// </summary>
      public const string OpencvCudacodecLibrary = "opencv_cudacodec300"; 
      /// <summary>
      /// The file name of the text library
      /// </summary>
      public const string OpencvTextLibrary = "opencv_text300"; 
      /// <summary>
      /// The file name of the face library
      /// </summary>
      public const string OpencvFaceLibrary = "opencv_face300"; 
      /// <summary>
      /// The file name of the ximgproc library
      /// </summary>
      public const string OpencvXimgprocLibrary = "opencv_ximgproc300"; 
      /// <summary>
      /// The file name of the xobjdetect library
      /// </summary>
      public const string OpencvXobjdetectLibrary = "opencv_xobjdetect300"; 
      /// <summary>
      /// The file name of the xfeatures2d library
      /// </summary>
      public const string OpencvXfeatures2dLibrary = "opencv_xfeatures2d300"; 
      /// <summary>
      /// The file name of the bgsegm library
      /// </summary>
      public const string OpencvBgsegmLibrary = "opencv_bgsegm300"; 
      /// <summary>
      /// The file name of the optflow library
      /// </summary>
      public const string OpencvOptflowLibrary = "opencv_optflow300";
	  
      /// <summary>
      /// The List of the opencv modules
      /// </summary>
	  public static List<String> OpenCVModuleList = new List<String>
	  {
        OpencvFFMpegLibrary,
	     OpenclLibrary,
	     OpencvCoreLibrary,
	     OpencvImgprocLibrary,
	     OpencvVideoLibrary,
	     OpencvFlannLibrary,
	     OpencvMlLibrary,
	     OpencvImgcodecsLibrary,
	     OpencvVideoioLibrary,
	     OpencvHighguiLibrary,
	     OpencvObjdetectLibrary,
	     OpencvFeatures2dLibrary,
	     OpencvCalib3dLibrary,
	     OpencvCudalegacyLibrary,
	     OpencvCudaarithmLibrary,
	     OpencvCudawarpingLibrary,
	     OpencvCudaLibrary,
	     OpencvCudafiltersLibrary,
	     OpencvCudaimgprocLibrary,
	     OpencvCudaoptflowLibrary,
	     OpencvCudastereoLibrary,
	     OpencvCudabgsegmLibrary,
	     OpencvCudafeatures2dLibrary,
	     OpencvPhotoLibrary,
	     OpencvSuperresLibrary,
	     OpencvStitchingLibrary,
	     OpencvVideostabLibrary,
	     OpencvShapeLibrary,
	     OpencvCudevLibrary,
	     OpencvCudacodecLibrary,
	     OpencvTextLibrary,
	     OpencvFaceLibrary,
	     OpencvXimgprocLibrary,
	     OpencvXobjdetectLibrary,
	     OpencvXfeatures2dLibrary,
	     OpencvBgsegmLibrary,
	     OpencvOptflowLibrary,
        ExternLibrary
      };

	  
   }
}
